--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/benzodoesdev/CustomAlerts
branches:
- master
projects:
  CustomAlerts:
    path: CustomAlerts/
  CustomAlertsExample:
    path: CustomAlertsExample/
...
